### ISSUE TITLE
unclear where jars are deployed

### ISSUE THREAD

**Issue by fs111** [branky/cascading.hive#1]
I was wondering if you have already deployed jars of this project and if so, in which repo they are. I searched conjars, but I did not find it. Thx!

**Comment by branky** [comment]
It's suppose to be conjars. I used mvn:deploy, but failed with authorization issue.

[INFO] --- maven-deploy-plugin:2.7:deploy (default-deploy) @ cascading-hive ---
Downloading: http://conjars.org/repo/cascading/cascading-hive/0.0.1-SNAPSHOT/maven-metadata.xml
Uploading: http://conjars.org/repo/cascading/cascading-hive/0.0.1-SNAPSHOT/cascading-hive-0.0.1-20140317.023148-1.jar  
14888/15863 KB  
Uploading: http://conjars.org/repo/cascading/cascading-hive/0.0.1-SNAPSHOT/cascading-hive-0.0.1-20140317.023148-1.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:16.471s
[INFO] Finished at: Mon Mar 17 10:33:39 CST 2014
[INFO] Final Memory: 9M/93M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project cascading-hive: Failed to deploy artifacts: Could not transfer artifact cascading:cascading-hive:jar:0.0.1-20140317.023148-1 from/to conjars (http://conjars.org/repo): Failed to transfer file: http://conjars.org/repo/cascading/cascading-hive/0.0.1-SNAPSHOT/cascading-hive-0.0.1-20140317.023148-1.jar. Return code is: 401, ReasonPhrase: Unauthorized.

Do you have any idea how can I get authorized?

**Comment by fs111** [comment]
Did you sign up for an account on conjars? Did you upload your ssh key? http://conjars.org/register

Also, you won't be able to upload the jar, if you are using the 'cascading' group id. Only we can use that. Once you have registered, you will be assigned one, that you can use.

**Comment by branky** [comment]
I have registered an account and uploaded my ssh pub key to the site.

 "you won't be able to upload the jar, if you are using the 'cascading' group id. Only we can use that."  
-- this might be the root cause.
But I tried to change the assigned group id to be "org.clojars.branky", still got same error:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project cascading-hive: Failed to deploy artifacts: Could not transfer artifact org.clojars.branky:cascading-hive:jar:0.0.1-20140317.122457-1 from/to conjars (http://conjars.org/repo): Failed to transfer file: http://conjars.org/repo/org/clojars/branky/cascading-hive/0.0.1-SNAPSHOT/cascading-hive-0.0.1-20140317.122457-1.jar. Return code is: 401, ReasonPhrase: Unauthorized.

**Comment by fs111** [comment]
I believe you have to setup your project like so to make it work with maven: http://maven.apache.org/plugins/maven-deploy-plugin/examples/deploy-ssh-external.html

**Comment by branky** [comment]
Yes, maven has been setup properly.

I just realized that I can't logon conjars through ssh:
$ ssh branky@conjars.org
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

Is this working for you?

**Comment by fs111** [comment]
you cannot log into conjars. You can only upload a jar/pom via scp

**Comment by branky** [comment]
I gave up with mvn deploy, scp works elegantly!

**Comment by cwensel** [comment]
fwiw, you should just be able to push using your conjars user/password over http. 

but good we have the scp option working as well.
